# Generated by Django 5.2.3 on 2025-06-30 22:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SensorData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("distance", models.FloatField()),
                ("temperature", models.FloatField()),
                ("humidity", models.FloatField()),
                ("accel_x", models.IntegerField()),
                ("accel_y", models.IntegerField()),
                ("accel_z", models.IntegerField()),
                ("gate_status", models.CharField(max_length=10)),
            ],
        ),
    ]
